[preferred]
default=gnome;gtk
# except for the xdg-desktop-portal-wlr supplied interfaces
org.freedesktop.impl.portal.Screencast=gnome;gtk
org.freedesktop.impl.portal.Screenshot=gnome;gtk
org.freedesktop.Notifications=gnome;gtk
 
