set -g default-terminal "screen-256color"

# make sure there is no delay when escaping
set -sg escape-time 0

set -g mouse on

#For Xorg based systems:
#bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xsel -i --clipboard"
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"

# plugins
run-shell $HOME/.config/tmux/plugins/tmux-resurrect/resurrect.tmux

# Wayland specific environment variables
set-option -g update-environment "DISPLAY WAYLAND_DISPLAY XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS HYPRLAND_INSTANCE_SIGNATURE SWAYSOCK SSH_AUTH_SOCK"

set -g mode-style 'reverse'
